# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'hbp_pipeline'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'hbp_pipeline'

# These configurations specify where dbt should look for different types of files.
model-paths: ["../../models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["../../data/processed"]
macro-paths: ["../../macros"]
snapshot-paths: ["snapshots"]

# directory as views. These settings can be overridden in the individual model
# files using the `{{ config(...) }}` macro.
models:
  hbp_pipeline:
    staging:
      +materialized: view
      +schema: STAGING
    intermediate:
      +materialized: view
      +schema: INTERMEDIATE
    marts:
      +materialized: table
      +schema: MARTS

seeds:
  hbp_pipeline:
    +schema: INGEST
    # Fixed deprecation structure by nesting properties using config keys
    customers_clean:
      +alias: dim_customers
    orders_clean:
      +alias: fct_orders
    products_clean:
      +alias: dim_products
