-- Distinct values for key columns
SELECT DISTINCT country FROM HBP_PRACTICE.RAW.CUSTOMERS;
SELECT DISTINCT status FROM HBP_PRACTICE.RAW.ORDERS;
SELECT DISTINCT category FROM HBP_PRACTICE.RAW.PRODUCTS;